// Registers the service worker generated by vite-plugin-pwa and wires the
// silent next-load update flow described in
// docs/superpowers/specs/2026-05-11-pwa-design.md.
//
// Update behavior:
//   - First-ever install (no existing controller) → let it install
//     normally; the next navigation will be SW-controlled.
//   - Update available (existing controller, new SW reaches 'installed') →
//     send SKIP_WAITING. The new SW activates immediately, but does NOT
//     reload existing tabs — the user picks up the new build on their next
//     cold load. This is the "silent next-load update" pattern.
//
// No banner UI. The bricking safety net is the SW's network-first strategy
// for navigation requests (configured in vite.config.ts).

const SW_URL = '/sw.js';

export function registerServiceWorker(): void {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
  // Wait for window load so the SW registration doesn't compete with
  // first-paint resources on slow networks.
  const start = () => {
    navigator.serviceWorker
      .register(SW_URL, { scope: '/' })
      .then((reg) => {
        handleRegistration(reg, { hasController: !!navigator.serviceWorker.controller });
      })
      .catch(() => { /* SW failed — app works fine without it */ });
  };
  if (document.readyState === 'complete') {
    start();
  } else {
    window.addEventListener('load', start, { once: true });
  }
}

export interface HandleOpts {
  /**
   * True when navigator.serviceWorker.controller exists at registration
   * time, i.e. the page is already being served by a previously installed
   * SW. Used to distinguish "update available" from "first install."
   */
  readonly hasController?: boolean;
}

export function handleRegistration(
  reg: ServiceWorkerRegistration,
  opts: HandleOpts = {},
): void {
  const hasController = opts.hasController ?? false;

  if (reg.waiting) {
    reg.waiting.postMessage({ type: 'SKIP_WAITING' });
  }

  reg.addEventListener('updatefound', () => {
    const installing = reg.installing;
    if (installing) watchInstalling(installing, hasController);
  });

  if (reg.installing) {
    watchInstalling(reg.installing, hasController);
  }
}

function watchInstalling(worker: ServiceWorker, hasController: boolean): void {
  worker.addEventListener('statechange', () => {
    if (worker.state === 'installed' && hasController) {
      worker.postMessage({ type: 'SKIP_WAITING' });
    }
  });
}
